model: "mlx-community/Qwen3-0.6B-bf16"
fine_tune_type: lora

optimizer: adamw

optimizer_config:
  adamw:
    betas: [0.9, 0.98]
    eps: 1e-6
    weight_decay: 0.01

learning_rate: 5e-5

lr_schedule:
  name: cosine_decay
  arguments:
    - 5e-5
    - 6000
    - 1e-6
  warmup: 500
  warmup_init: 0.0

iters: 6000

save_every: 1000

batch_size: 4
grad_accumulation_steps: 32

max_seq_length: 2048

num_layers: 28

grad_checkpoint: true

data: "new_data"
prompt_feature: "question"
completion_feature: "answer"
train: true
adapter_path: "adapters-run-3"

lora_parameters:
  keys: [
    "self_attn.q_proj",
    "self_attn.v_proj",
    "self_attn.k_proj",
    "self_attn.o_proj",
    "self_attn.gate_proj",
    "self_attn.up_proj",
    "self_attn.down_proj"
  ]
  rank: 32
  scale: 32.0
  dropout: 0.05
