"""Assemble the Zenodo deposit for the revision-v2 paper.

Writes deposit/zenodo-v2/ with one archive per licence and purpose, a README
(also used as the Zenodo description) and SHA256SUMS.txt:

  socratiq-v2-data.zip             paired training data, subsets, canonical examples (CC BY 4.0)
  socratiq-v2-runs.zip             training logs and manifests, all predictions (CC BY 4.0)
  socratiq-v2-evidence.zip         the tables and CSVs behind every reported number (CC BY 4.0)
  socratiq-v2-adapters-qwen3.zip   eight Qwen3 LoRA adapters (Apache 2.0)
  socratiq-v2-adapters-llama3.2.zip  two Llama 3.2 LoRA adapters (Llama 3.2 Community License)
  socratiq-code-<tag>.zip          the code at a git tag (MIT), added with --code-tag

Run files are copied unchanged, so every hash in the manifests still verifies.
Nothing outside the listed directories is included, and no .env file can be.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
import zipfile
from collections.abc import Iterable, Sequence
from pathlib import Path

from src.revision_v2.protocol import REPOSITORY_ROOT

OUTPUT = REPOSITORY_ROOT / "deposit/zenodo-v2"
LICENSE_TEXTS = REPOSITORY_ROOT / "deposit/licenses"
README = REPOSITORY_ROOT / "deposit/README_ZENODO.md"
RUNS = Path("runs/revision_v2")
FIXED_TIMESTAMP = (2026, 10, 7, 0, 0, 0)
LLAMA_NOTICE = (
    "Llama 3.2 is licensed under the Llama 3.2 Community License, "
    "Copyright © Meta Platforms, Inc. All Rights Reserved.\n"
)
LLAMA_NAMES = {
    "llama3.2_1b_socratic_lr8e-5": "Llama-3.2-1B-Instruct-socratiq-socratic-lora",
    "llama3.2_1b_non_socratic_lr8e-5": "Llama-3.2-1B-Instruct-socratiq-non-socratic-lora",
}
CC_BY = (
    "The contents of this archive are released under the Creative Commons "
    "Attribution 4.0 International licence (CC BY 4.0):\n"
    "https://creativecommons.org/licenses/by/4.0/\n\n"
    "The synthetic problems were generated by GPT-5-mini from the GSM8K training split "
    "(Cobbe et al., 2021; MIT licence). Evaluation predictions quote items from GSM8K, "
    "MultiArith, SVAMP and GSM-Hard, which remain under their original licences.\n"
)


class DepositError(RuntimeError):
    """Raised when the deposit would be incomplete or unsafe."""


def files_under(*roots: Path) -> list[Path]:
    """Every regular file under the roots, relative to the repository, sorted."""
    found = []
    for root in roots:
        absolute = REPOSITORY_ROOT / root
        if absolute.is_file():
            found.append(root)
            continue
        if not absolute.is_dir():
            raise DepositError(f"missing {root}")
        found.extend(
            p.relative_to(REPOSITORY_ROOT)
            for p in sorted(absolute.rglob("*"))
            if p.is_file() and p.name != ".DS_Store"
        )
    for path in found:
        if path.name.startswith(".env"):
            raise DepositError(f"refusing to package {path}")
    return found


def write_zip(
    name: str,
    members: Iterable[tuple[Path, str]],
    extra: dict[str, str] | None = None,
) -> Path:
    """Write an archive from (source, name in archive) pairs plus small text files."""
    target = OUTPUT / name
    with zipfile.ZipFile(target, "w") as archive:
        for text_name, text in (extra or {}).items():
            info = zipfile.ZipInfo(text_name, date_time=FIXED_TIMESTAMP)
            archive.writestr(info, text, compress_type=zipfile.ZIP_DEFLATED)
        for source, arcname in members:
            compression = (
                zipfile.ZIP_STORED
                if source.suffix == ".safetensors"
                else zipfile.ZIP_DEFLATED
            )
            archive.write(REPOSITORY_ROOT / source, arcname, compress_type=compression)
    return target


def license_text(name: str) -> str:
    """Official licence text saved under deposit/licenses/."""
    path = LICENSE_TEXTS / name
    if not path.is_file():
        raise DepositError(f"missing licence text {path}")
    return path.read_text("utf-8")


def build_data() -> Path:
    """Paired data, subsets, canonical examples and their manifests."""
    paths = files_under(
        Path("data/revision_v2"),
        Path("data/reviewer_rerun/canonical/accepted.jsonl"),
        Path("data/reviewer_rerun/manifests"),
        Path("configs/revision_v2/dataset_manifest.json"),
    )
    return write_zip(
        "socratiq-v2-data.zip", ((p, str(p)) for p in paths), {"LICENSE.txt": CC_BY}
    )


def build_runs() -> Path:
    """Everything the runs wrote except adapter weights."""
    paths = [p for p in files_under(RUNS) if "/adapter/" not in str(p)]
    return write_zip(
        "socratiq-v2-runs.zip", ((p, str(p)) for p in paths), {"LICENSE.txt": CC_BY}
    )


def build_evidence() -> Path:
    """Archive the evidence directory behind every reported number."""
    paths = files_under(Path("manuscript/revision-v2/evidence"))
    return write_zip(
        "socratiq-v2-evidence.zip",
        ((p, str(p.relative_to("manuscript/revision-v2"))) for p in paths),
        {"LICENSE.txt": CC_BY},
    )


def adapter_files(run_id: str) -> list[Path]:
    """Return the final adapter weights and config of one run."""
    directory = RUNS / "training" / run_id / "adapter"
    paths = files_under(directory)
    names = sorted(p.name for p in paths)
    if names != ["adapter_config.json", "adapters.safetensors"]:
        raise DepositError(f"unexpected adapter files for {run_id}: {names}")
    return paths


def build_qwen_adapters() -> Path:
    """Eight Qwen3 adapters under Apache 2.0."""
    runs = sorted(p.name for p in (REPOSITORY_ROOT / RUNS / "training").glob("qwen3_*"))
    members = [(p, f"{run}/{p.name}") for run in runs for p in adapter_files(run)]
    readme = (
        "LoRA adapters for the Qwen3 base models listed in each adapter_config.json. "
        "The base models are released by the Qwen team under Apache 2.0, and these "
        "adapters are released under the same licence (LICENSE).\n"
    )
    return write_zip(
        "socratiq-v2-adapters-qwen3.zip",
        members,
        {"LICENSE": license_text("QWEN3_LICENSE.txt"), "README.txt": readme},
    )


def build_llama_adapters() -> Path:
    """Two Llama 3.2 adapters with the licence, use policy and notice Meta requires."""
    members = [
        (p, f"{name}/{p.name}")
        for run, name in LLAMA_NAMES.items()
        for p in adapter_files(run)
    ]
    readme = (
        "Built with Llama.\n\n"
        "LoRA adapters for Llama-3.2-1B-Instruct (Meta's weights in MLX bfloat16). "
        "They are distributed under the Llama 3.2 Community License (LICENSE) and its "
        "Acceptable Use Policy (USE_POLICY.md). See NOTICE.txt.\n"
    )
    return write_zip(
        "socratiq-v2-adapters-llama3.2.zip",
        members,
        {
            "LICENSE": license_text("LLAMA_3.2_LICENSE.txt"),
            "USE_POLICY.md": license_text("LLAMA_3.2_USE_POLICY.md"),
            "NOTICE.txt": LLAMA_NOTICE,
            "README.txt": readme,
        },
    )


def build_code(tag: str) -> Path:
    """Archive the repository at a git tag, as git exports it (tracked files only)."""
    target = OUTPUT / f"socratiq-code-{tag}.zip"
    subprocess.run(
        [
            "git",
            "archive",
            "--format=zip",
            f"--prefix=socratiq-{tag}/",
            "-o",
            str(target),
            tag,
        ],
        cwd=REPOSITORY_ROOT,
        check=True,
    )
    with zipfile.ZipFile(target) as archive:
        if any(Path(n).name.startswith(".env") for n in archive.namelist()):
            target.unlink()
            raise DepositError(f"tag {tag} tracks a .env file")
    return target


def sha256(path: Path) -> str:
    """SHA-256 of a file."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def copy_readme() -> Path:
    """Copy the deposit README, which is also the Zenodo description."""
    if not README.is_file():
        raise DepositError(f"missing {README}")
    target = OUTPUT / "README.md"
    target.write_text(README.read_text("utf-8"), "utf-8")
    return target


def write_checksums() -> Path:
    """SHA256SUMS.txt for every file in the deposit except itself."""
    lines = [
        f"{sha256(p)}  {p.name}"
        for p in sorted(OUTPUT.iterdir())
        if p.is_file() and p.name != "SHA256SUMS.txt"
    ]
    target = OUTPUT / "SHA256SUMS.txt"
    target.write_text("\n".join(lines) + "\n", "utf-8")
    return target


BUILDERS = {
    "data": build_data,
    "runs": build_runs,
    "evidence": build_evidence,
    "qwen": build_qwen_adapters,
    "llama": build_llama_adapters,
}


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=["build", "code", "checksums"])
    parser.add_argument("--code-tag", help="git tag to archive (command: code)")
    parser.add_argument(
        "--only",
        nargs="+",
        choices=sorted(BUILDERS),
        help="rebuild only these archives (command: build), so unchanged uploads stay valid",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Build the deposit archives."""
    args = _parser().parse_args(argv)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    if args.command == "build":
        for name in args.only or BUILDERS:
            path = BUILDERS[name]()
            print(f"{path.name}: {path.stat().st_size / 1e6:.1f} MB")
    elif args.command == "code":
        if not args.code_tag:
            raise DepositError("--code-tag is required")
        path = build_code(args.code_tag)
        print(f"{path.name}: {path.stat().st_size / 1e6:.1f} MB")
    copy_readme()
    write_checksums()
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
